config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'welcome#index'

  get '/my-orders', to: 'orders#show', as: 'ordered_products_page'

  get '/checkout', to: 'orders#checkout', as: 'checkout_page'

  get '/user/profile', to: 'users#index', as: 'profile_page'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
  end

  def checkout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html ng-app>
  <head>
    <title><%= yield(:title) %></title>

    <% unless params[:controller] == 'static' -%>
      <%= tag 'meta', name: 'description', content: yield(:description) %>
    <% end -%>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= yield :meta_tags %>
    <%= stylesheet_link_tag 'application' %>

    <%= yield :head_javascripts %>

    <%= yield :stylesheets %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:javascripts) %>
  </body>
</html>

app/views/orders/checkout.html.erb
<section class='checkout'>
  <h1>Endereço de entrega</h1>
  <div class='addresses'>
    <ul>
      <li class='default-address'>
        <div class='address-holder address-cep'>
          <label>CEP:</label><span class='cep'>01153-010</span>
        </div>
        <div class='address-holder address'>
          <label>Endereço:</label><span>Rua Dr. Sérgio Meira</span>
        </div>
        <div class='address-holder address-number'>
          <label>nº:</label><span>230</span>
        </div>
        <div class='address-holder'>
          <label>Bairro:</label><span>Barra Funda De Pirapora</span>
        </div>
        <div class='address-holder'>
          <label>Cidade:</label><span>São Paulo</span>
        </div>
        <div class='address-holder'>
          <label>Estado:</label>
          <select disabled=true>
            <option value="sao-paulo">São Paulo</option>
          </select>
        </div>
      </li>
    </ul>

    <div class='confirm-action'>
      <%= link_to 'Confirmar', profile_page_path, class: 'confirm-orders' %>
    </div>
  </div>
</section>

app/views/orders/show.html.erb
<% content_for :title, "Meus Pedidos" %>
<section class='orders'>
  <div class='title'>
    <h1>Meu carrinho</h1>
  </div>
  <div class='products-holder'>
    <header>
      <ul class="products-header">
        <li class="products-header-item header-products">produto(s)</li>
        <li class="products-header-item header-quantity">quantidade</li>
        <li class="products-header-item header-total">total</li>
      </ul>
    </header>
    <ul class='my-products'>
      <li class='product'>
        <ul class='products-info'>
          <li class='product-item description'>
            <div class='info'>
              <%= image_tag 'lapis.jpg' %>
              <h3>Lápis de Cor</h3>
              <p class='product-description'>Lápis Faber Castel - 12 cores</p>
            </div>
          </li>
          <li class='product-item quantity'>
          <p><span ng-click="count = count - 1" ng-init="count=1" class='quantity-control remove'>-</span>{{count}}<span ng-click="count = count + 1" ng-init="count=1" class='quantity-control add'>+</span></p>
          </li>
          <li class='product-item price'>
            <p>R$ 10,00</p>
          </li>
        </ul>
      </li>
      <li class='product'>
        <ul class='products-info'>
          <li class='product-item description'>
            <div class='info'>
              <%= image_tag 'planet.jpg' %>
              <h3>Planeta Terra</h3>
              <p class='product-description'>Planeta Terra - C/ Pequenos Defeitos</p>
            </div>
          </li>
          <li class='product-item quantity'>
            <p><span class='quantity-control remove'>-</span>1<span class='quantity-control add'>+</span></p>
          </li>
          <li class='product-item price'>
            <p>R$ 49,70</p>
          </li>
        </ul>
      </li>
    </ul>

    <div class='confirm-action'>
      <%= link_to 'Finalizar pedido', checkout_page_path, class: 'confirm-orders' %>
    </div>
</section>

app/views/users/index.html.erb
<% content_for :title, "Eyng's Market" %>
<section class='profile'>
  <header>
    <div>
      <h1>Olá <span class='user'></span>,</h1>
    </div>
  </header>
  <div class='meus-pedidos'>
    <h3>Histórico de Pedidos</h3>
    <ul>
      <li class='product-info'>
        <div>
          <%= image_tag 'lapis.jpg' %>
          <p>Lápis de cor Faber Castel - 12 cores</p>
        </div>
      </li>
      <li class='product-info'>
        <div class='product-info'>
          <%= image_tag 'planet.jpg' %>
          <p>Planeta Terra</p>
        </div>
      </li>
    </ul>
  </div>
  <div class='meus-dados'>
    <h3>Meus Dados</h3>
    <ul>
      <h4>Endereço</h4>
      <li>Rua Dr. Sergio Meira, nº 230</li>
      <li>Barra Funda, São Paulo - SP</li>
    </ul>
  </div>
</section>
<% content_for :javascripts do %>
  <script>
    $(function () {
      var userName = $.cookie('user_name') ? $.cookie('user_name') : 'TESTE WALMART',
          userNameHolder = $('.profile .user');

      userNameHolder.text(userName);
    });
  </script>
<% end %>

app/views/welcome/index.html.erb
<% content_for :title, "Eyng's Market" %>
<section>
  <div class='user-name'>
    <input name='user' type='text' ng-model='name' placeholder='Type your name'>
  </div>
</section>
<section class='welcome'>
  <header>
    <div>
      <h1>Olá {{name}}, bem-vindo ao Eyng's Market</h1>
      <p>Aqui você encontra todos os produtos que desejar. Desde uma simples borracha até seu próprio planeta!</p>
      <p>Fique à vontade e boas compras!</p>

      <%= link_to "Lista de produtos pedidos", ordered_products_page_path, class: 'confirm' %>
    </div>
  </header>
</section>
<footer>
  <p class='copyright'>Todos os direitos reservados</p>
</footer>